import sphinx_rtd_theme

# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'Regelsamlingen'
copyright = '2021, Universitetet i Bergen'
author = 'UiB'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
        'sphinx_rtd_theme',
        ]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'nb_NO'  

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [ ]


# -- Options for HTML output -------------------------------------------------

# Katalog som inneholder statiske filer som skal inkluderes
html_extra_path = ['extra']

# Skjul informasjon om Sphinx og sphinx-rtd-theme i footer.
html_show_sphinx = False

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'
html_theme_options = {
        # Sidemenyen følger innholdet nedover siden
        'sticky_navigation': True,
        # Sidemenyen kan slås sammen og utvides
        'collapse_navigation': True,
        # Antall underkataloger som skal vises i menyen
        'navigation_depth': 4,
        # Skjul versjonen av dokumentasjonen
        'display_version': False,
        # Vis navnet på prosjektet over logoen øverst til venstre
	'logo_only': False,
        # Skjul "Next"- og "Previous"-knapper for å navigere mellom sider
	'prev_next_buttons_location': None,
        # Vis ikon bak eksterne lenker for å vise at de leder vekk fra regelsamlingen
	'style_external_links': True,
        }

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
# Logo øverst til venstre
html_logo = "UiB-emblem_white.svg"

# Definer hvilke stilark som skal overskrive standardmalen
def setup(app):
        app.add_css_file('css/uib.css')
